// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ZendeskXamarinAndroid.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ZendeskXamarinAndroid.Core.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string loadingPleaseWait {
            get {
                return ResourceManager.GetString("loadingPleaseWait", resourceCulture);
            }
        }
        
        internal static string loadSections {
            get {
                return ResourceManager.GetString("loadSections", resourceCulture);
            }
        }
        
        internal static string loadTickets {
            get {
                return ResourceManager.GetString("loadTickets", resourceCulture);
            }
        }
        
        internal static string sendImage {
            get {
                return ResourceManager.GetString("sendImage", resourceCulture);
            }
        }
        
        internal static string takePhoto {
            get {
                return ResourceManager.GetString("takePhoto", resourceCulture);
            }
        }
        
        internal static string chooseShare {
            get {
                return ResourceManager.GetString("chooseShare", resourceCulture);
            }
        }
        
        internal static string chooseExisting {
            get {
                return ResourceManager.GetString("chooseExisting", resourceCulture);
            }
        }
        
        internal static string imageNotUploaded {
            get {
                return ResourceManager.GetString("imageNotUploaded", resourceCulture);
            }
        }
        
        internal static string sendComment {
            get {
                return ResourceManager.GetString("sendComment", resourceCulture);
            }
        }
        
        internal static string loadComments {
            get {
                return ResourceManager.GetString("loadComments", resourceCulture);
            }
        }
        
        internal static string loadArticles {
            get {
                return ResourceManager.GetString("loadArticles", resourceCulture);
            }
        }
    }
}
